use super::*;
pub fn today()->String{let d=js_sys::Date::new_0();format!("{:04}-{:02}-{:02}",d.get_full_year(),d.get_month()+1,d.get_date())}
fn target(e:&Event)->Option<Element>{e.target()?.dyn_into::<Element>().ok()}
fn input_value(el:&Element)->(String,bool){if let Some(e)=el.dyn_ref::<HtmlInputElement>(){(e.value(),e.checked())}else if let Some(e)=el.dyn_ref::<HtmlSelectElement>(){(e.value(),false)}else{(String::new(),false)}}
pub fn install(){
 let click=Closure::<dyn FnMut(Event)>::new(|e:Event|{let Some(el)=target(&e).and_then(|e|e.closest("[data-action]").ok().flatten())else{return};let Some(action)=el.get_attribute("data-action")else{return};if action=="backdrop"&&e.target()!=Some(el.clone().into()){return}action_dispatch(&action);});document().add_event_listener_with_callback("click",click.as_ref().unchecked_ref()).unwrap();click.forget();
 let key=Closure::<dyn FnMut(KeyboardEvent)>::new(|e:KeyboardEvent|{let key=if e.code()=="Space"||e.key()==" "{"space".into()}else{e.key().to_lowercase()};let s=Shortcut{key:key.clone(),code:e.code(),shift:e.shift_key(),ctrl:e.ctrl_key(),alt:e.alt_key(),meta:e.meta_key()};if with(|a|a.recording){e.prevent_default();if key=="escape"{change(|a|a.recording=false);render();return}if !e.repeat()&&s.valid(){change(|a|{a.shortcut=s.clone();a.recording=false;});local_set("icon-studio-search-shortcut",&json!(s).to_string());persist_preferences();render();}return}
  if !e.repeat()&&with(|a|a.shortcut.matches(&s)){e.prevent_default();action_dispatch("quick");return}
  if key=="escape"{action_dispatch("close");return}if with(|a|a.modal=="quick"){let n=with(|a|a.quick_results.len());if n==0{return}let cols=if window().inner_width().ok().and_then(|v|v.as_f64()).unwrap_or(1000.)<700.{3}else{5};let delta=match key.as_str(){"arrowright"=>1,"arrowleft"=>-1,"arrowdown"=>cols,"arrowup"=>-cols,_=>0};if delta!=0{e.prevent_default();change(|a|a.quick_index=(a.quick_index as i32+delta).clamp(0,n as i32-1)as usize);render();}else if key=="enter"{e.prevent_default();if let Some(i)=with(|a|a.quick_results.get(a.quick_index).cloned()){add_icon(i)}}return}
  let typing=target(&e.clone().into()).is_some_and(|e|["INPUT","TEXTAREA","SELECT"].contains(&e.tag_name().as_str())||e.get_attribute("contenteditable").is_some());if typing{return}if (e.ctrl_key()||e.meta_key())&&key=="z"{e.prevent_default();action_dispatch(if e.shift_key(){"redo"}else{"undo"})}if key=="enter"{if let Some(el)=target(&e.clone().into()).and_then(|el|el.get_attribute("data-action")){e.prevent_default();action_dispatch(&el)}}});document().add_event_listener_with_callback("keydown",key.as_ref().unchecked_ref()).unwrap();key.forget();
 let input=Closure::<dyn FnMut(Event)>::new(|e:Event|{if let Some(el)=target(&e){handle_input(el,false)}});document().add_event_listener_with_callback("input",input.as_ref().unchecked_ref()).unwrap();input.forget();
 let changed=Closure::<dyn FnMut(Event)>::new(|e:Event|{if let Some(el)=target(&e){handle_input(el,true)}});document().add_event_listener_with_callback("change",changed.as_ref().unchecked_ref()).unwrap();changed.forget();
 let pointer=Closure::<dyn FnMut(Event)>::new(|e:Event|{if target(&e).is_some_and(|el|el.has_attribute("data-style")){snapshot();}});document().add_event_listener_with_callback("pointerdown",pointer.as_ref().unchecked_ref()).unwrap();pointer.forget();
 let over=Closure::<dyn FnMut(DragEvent)>::new(|e:DragEvent|{e.prevent_default();});document().add_event_listener_with_callback("dragover",over.as_ref().unchecked_ref()).unwrap();over.forget();
 let drop=Closure::<dyn FnMut(DragEvent)>::new(|e:DragEvent|{e.prevent_default();if let Some(files)=e.data_transfer().and_then(|d|d.files()){import_files(files)}});document().add_event_listener_with_callback("drop",drop.as_ref().unchecked_ref()).unwrap();drop.forget();
 let drag=Closure::<dyn FnMut(DragEvent)>::new(|e:DragEvent|{if target(&e.clone().into()).is_some_and(|e|e.get_attribute("data-action").as_deref()==Some("drag")){e.prevent_default();action_dispatch("drag");}});document().add_event_listener_with_callback("dragstart",drag.as_ref().unchecked_ref()).unwrap();drag.forget();
 // Paste support uses ClipboardEvent's transferable files through Reflect to avoid injecting app logic.
 let paste=Closure::<dyn FnMut(Event)>::new(|e:Event|{if let Ok(data)=js_sys::Reflect::get(&e,&"clipboardData".into()){if let Ok(files)=js_sys::Reflect::get(&data,&"files".into()){if let Ok(files)=files.dyn_into::<FileList>(){if files.length()>0{e.prevent_default();import_files(files)}}}}});document().add_event_listener_with_callback("paste",paste.as_ref().unchecked_ref()).unwrap();paste.forget();
}
fn patch_preview(){with(|a|{if let Some(it)=a.items.get(a.active){if let Some(img)=document().get_element_by_id("preview"){let _=img.set_attribute("src",&svg_data(&build_svg(it,1024,a.glyph_only)));}if let Some(img)=document().get_element_by_id(&format!("thumb-{}",a.active)){let _=img.set_attribute("src",&svg_data(&build_svg(it,80,false)));}}});}
fn handle_input(el:Element,committed:bool){
 if let Some(input)=el.dyn_ref::<HtmlInputElement>(){if input.type_()=="file"{if committed{if let Some(files)=input.files(){import_files(files)}}return}}
 let (value,checked)=input_value(&el);let field=el.get_attribute("data-field").unwrap_or_default();
 if let Some(key)=el.get_attribute("data-style"){
  let def=defaults()[&key].clone();let v=if def.is_boolean(){json!(checked)}else if def.is_number(){json!(value.parse::<f64>().unwrap_or(0.))}else{json!(value)};
  if key.to_lowercase().contains("color")&&key!="iconColorMode"&&!valid_color(v.as_str().unwrap_or("")){return}
  change(|a|{if let Some(it)=a.items.get_mut(a.active){it.style[&key]=v;it.style=clean_style(&it.style);}});patch_preview();if let Some(v)=document().get_element_by_id(&format!("value-{key}")){v.set_text_content(Some(&value));}
  if committed{persist();if ["removeBg","bgRemoveMode","bgTolerance","bgRemoveColor","edgeOnly"].contains(&key.as_str()){remove_background();}render();}return
 }
 match field.as_str(){"search"=>{change(|a|a.query=value);refresh_search(false)},"quick-search"=>{change(|a|a.quick_query=value);refresh_search(true)},"category"=>{change(|a|a.category=value);refresh_search(false)},"shortcut-preset"=>{if let Ok(i)=value.parse::<usize>(){let s=Shortcut::preset(i);change(|a|a.shortcut=s.clone());local_set("icon-studio-search-shortcut",&json!(s).to_string());persist_preferences();render();}},"look-name"=>{change(|a|a.look_name=value);},"export-size"=>{change(|a|a.export_size=value.parse().unwrap_or(1024));},"glyph-only"=>{change(|a|a.glyph_only=checked);patch_preview();},"pack-search"=>{change(|a|a.pack_query=value);render()},"archive-project"=>{change(|a|a.archive_project=value);load_archive();},_=>{
 if let Some(key)=field.strip_prefix("rename-"){change(|a|match key{"template"=>a.rule.template=value,"prefix"=>a.rule.prefix=value,"suffix"=>a.rule.suffix=value,"find"=>a.rule.find=value,"replace"=>a.rule.replace=value,"start"=>a.rule.start=value.parse().unwrap_or(1),"padding"=>a.rule.padding=value.parse().unwrap_or(0),"case"=>a.rule.case=value,"regex"=>a.rule.regex=checked,"caseSensitive"=>a.rule.case_sensitive=checked,_=>{}});render()}
 else if let Some(key)=field.strip_prefix("pack-"){change(|a|{if checked{a.pack_selection.insert(key.into());}else{a.pack_selection.remove(key);}});}
 else if let Some(key)=field.strip_prefix("setting-"){if committed{let v=if key=="track"{json!(value.parse::<u32>().unwrap_or(2).clamp(1,99))}else{json!(value)};let mut patch=json!({});patch[key]=v;spawn_local(async move{match api("updateSettings",patch).await{Ok(s)=>{change(|a|a.settings=s);render()},Err(e)=>toast(e)}});}}
 }}
}
fn active()->Option<Item>{with(|a|a.items.get(a.active).cloned())}
fn selected_or_active(){change(|a|{if a.selected.is_empty(){if let Some(it)=a.items.get(a.active){a.selected.insert(it.id.clone());}}});}
fn set_style(key:&str,v:Value){mutate(|a|{if let Some(it)=a.items.get_mut(a.active){it.style[key]=v;it.style=clean_style(&it.style);}});}
pub fn action_dispatch(action:&str){
 if let Some(id)=action.strip_prefix("add:"){if let Some((p,n))=id.split_once(':'){add_icon(Icon{prefix:p.into(),name:n.into()})}return}
 if let Some(id)=action.strip_prefix("favorite:"){let mut v:Vec<String>=local_get("icon-studio-favorites").and_then(|v|serde_json::from_str(&v).ok()).unwrap_or_default();if v.iter().any(|s|s==id){v.retain(|s|s!=id)}else{v.push(id.into())}local_set("icon-studio-favorites",&json!(v).to_string());persist_preferences();if with(|a|a.tab=="favorites"){refresh_search(false)}else{render()}return}
 if let Some(idx)=action.strip_prefix("active:").and_then(|s|s.parse::<usize>().ok()){change(|a|{a.active=idx.min(a.items.len().saturating_sub(1));a.inspector_open=false;});render();return}
 if let Some(idx)=action.strip_prefix("select:").and_then(|s|s.parse::<usize>().ok()){change(|a|{if let Some(it)=a.items.get(idx){let id=it.id.clone();if !a.selected.remove(&id){a.selected.insert(id);}}});render();return}
 if let Some(key)=action.strip_prefix("style:"){if let Some((k,v))=key.split_once(':'){set_style(k,json!(v))}return}
 if let Some(radius)=action.strip_prefix("radius:"){set_style("borderRadius",json!(radius.parse::<f64>().unwrap_or(22.5)));return}
 if let Some(p)=action.strip_prefix("panel:"){change(|a|a.panel=p.into());render();return}
 if let Some(p)=action.strip_prefix("tab:"){change(|a|a.tab=p.into());refresh_search(false);return}
 if let Some(p)=action.strip_prefix("palette:"){if let Some((target,i))=p.split_once(':'){if let Some((_,c,d))=i.parse::<usize>().ok().and_then(|i|ui::PALETTES.get(i)){mutate(|a|{if let Some(it)=a.items.get_mut(a.active){if target=="bg"{it.style["bgColor1"]=json!(c);it.style["bgColor2"]=json!(d);}else{it.style["iconColorMode"]=json!("gradient");it.style["iconColor1"]=json!(c);it.style["iconColor2"]=json!(d);}}});}}return}
 if let Some(p)=action.strip_prefix("solid:"){if let Some((target,c))=p.split_once(':'){if valid_color(c){mutate(|a|{if let Some(it)=a.items.get_mut(a.active){let(mode,color)=if target=="bg"{("bgType","bgColor1")}else{("iconColorMode","iconColor1")};it.style[mode]=json!("solid");it.style[color]=json!(c);}});}}return}
 if let Some(id)=action.strip_prefix("look-apply:").and_then(|s|s.parse::<usize>().ok()){let look=with(|a|a.looks.get(id).cloned());if let Some(look)=look{mutate(|a|{for it in &mut a.items{if a.selected.is_empty()||a.selected.contains(&it.id){let removal=it.style.clone();it.style=clean_style(&look["style"]);for key in ["removeBg","bgTolerance","bgRemoveMode","bgRemoveColor","edgeOnly"]{it.style[key]=removal[key].clone();}}}a.modal.clear();});let project=with(|a|a.project.clone());if with(|a|a.native){spawn_local(async move{if let Err(e)=api("setProjectLook",json!({"id":project["id"],"look":look})).await{toast(e)}});}}return}
 if let Some(id)=action.strip_prefix("look-delete:").and_then(|s|s.parse::<usize>().ok()){change(|a|{if id<a.looks.len(){a.looks.remove(id);}});persist();render();return}
 if let Some(key)=action.strip_prefix("folder:"){let key=key.to_string();spawn_local(async move{match api("chooseFolder",json!({"key":key})).await{Ok(v)=>{change(|a|a.settings=v);render()},Err(e)=>toast(e)}});return}
 if let Some(id)=action.strip_prefix("archive-pool:"){archive_action("pool",id);return}if let Some(id)=action.strip_prefix("archive-timeline:"){archive_action("timeline",id);return}if let Some(id)=action.strip_prefix("archive-reveal:"){archive_action("reveal",id);return}
 match action{
 "dismiss-announcement"=>{local_set("icon-studio-announcement-expanded-library-2026-10","dismissed");render()},
 "quick"=>{change(|a|{a.modal="quick".into();a.quick_query.clear();});refresh_search(true);if let Some(el)=document().get_element_by_id("quick-input").and_then(|e|e.dyn_into::<HtmlInputElement>().ok()){let _=el.focus();}},
 "close"|"backdrop"=>{change(|a|{a.modal.clear();a.recording=false;});render()},"dismiss"=>{change(|a|a.toast.clear());render()},
 "settings"|"looks"|"project"|"export"=>{change(|a|a.modal=action.into());render()},"archive"=>{change(|a|a.modal="archive".into());load_archive()},
 "library"=>{change(|a|a.library_open=!a.library_open);render()},"inspector"=>{change(|a|a.inspector_open=!a.inspector_open);render()},
 "theme"|"theme-dark"|"theme-light"=>{let theme=change(|a|{a.theme=if action=="theme-dark"||action=="theme"&&a.theme=="light"{"dark".into()}else{"light".into()};a.theme.clone()});local_set("icon-studio-theme",&theme);persist_preferences();render()},
 "pin"=>{let top=!with(|a|flag(&a.settings,"alwaysOnTop"));spawn_local(async move{match api("setAlwaysOnTop",json!({"value":top})).await{Ok(v)=>{change(|a|a.settings["alwaysOnTop"]=v);render()},Err(e)=>toast(e)}})},
 "record"=>{change(|a|a.recording=!a.recording);render()},"import"=>file_picker("file-input"),"project-import"|"looks-import"=>file_picker("project-input"),
 "checker"=>{change(|a|a.checker=!a.checker);render()},"glyph-only"=>{change(|a|a.glyph_only=!a.glyph_only);render()},"zoom-in"|"zoom-out"|"zoom-reset"=>{change(|a|a.zoom=if action=="zoom-reset"{1.}else{(a.zoom+if action=="zoom-in"{0.1}else{-0.1}).clamp(0.2,2.)});render()},
 "undo"|"redo"=>{change(|a|{if action=="undo"{if let Some(previous)=a.undo.pop(){a.redo.push(a.items.clone());a.items=previous;}}else if let Some(next)=a.redo.pop(){a.undo.push(a.items.clone());a.items=next;}a.active=a.active.min(a.items.len().saturating_sub(1));a.selected.retain(|id|a.items.iter().any(|it|&it.id==id));});persist();render()},
 "select-all"=>{change(|a|{if a.selected.len()==a.items.len(){a.selected.clear()}else{a.selected=a.items.iter().map(|i|i.id.clone()).collect()}});render()},
 "rename"|"rename-current"=>{change(|a|{if action=="rename-current"{a.selected.clear()}if a.selected.is_empty(){if let Some(it)=a.items.get(a.active){a.selected.insert(it.id.clone());}}a.modal="rename".into();a.rule=RenameRule::default();});render()},
 "rename-apply"=>{let rows=with(|a|rename(&a.items,&a.selected,&a.rule,&today()));match rows{Ok(rows)=>mutate(|a|{for(id,n)in rows{if let Some(it)=a.items.iter_mut().find(|i|i.id==id){it.name=n}}a.modal.clear();}),Err(e)=>toast(e)}},
 "duplicate"=>{selected_or_active();mutate(|a|{let chosen:Vec<_>=a.items.iter().filter(|i|a.selected.contains(&i.id)).cloned().collect();let count=chosen.len().min(200-a.items.len());for mut it in chosen.into_iter().take(count){it.id=uuid();it.name=unique_names(vec![format!("{} copy",it.name)],a.items.iter().map(|i|i.name.clone()).collect())[0].clone();a.items.push(it);}a.active=a.items.len().saturating_sub(1);});},
 "delete"=>{selected_or_active();mutate(|a|{a.items.retain(|it|!a.selected.contains(&it.id));a.active=a.active.min(a.items.len().saturating_sub(1));a.selected.clear();});},
 "new"=>{mutate(|a|{a.items.clear();a.selected.clear();a.active=0;a.modal.clear();});},
 "reset"=>mutate(|a|{if let Some(it)=a.items.get_mut(a.active){it.style=defaults();}}),
 "batch-style"=>{if let Some(it)=active(){if with(|a|a.selected.is_empty()){toast("Select icons in the collection first");return}mutate(|a|{for target in &mut a.items{if a.selected.contains(&target.id){target.style=it.style.clone();target.processed_image.clear();}}});toast("Style applied to selected icons");}},
 "look-save"=>{change(|a|a.modal="looks".into());render()},
 "look-save-confirm"=>{let name=with(|a|a.look_name.clone());if name.trim().is_empty(){toast("Name this look first");return}if let Some(it)=active(){let look=json!({"id":uuid(),"name":safe_name(&name),"style":look_style(&it.style)});change(|a|{a.looks.push(look.clone());a.look_name.clear();});persist();render();if with(|a|a.native){let id=with(|a|a.project["id"].clone());spawn_local(async move{if let Err(e)=api("setProjectLook",json!({"id":id,"look":look})).await{toast(e)}});}}},
 "png"|"svg"|"copy-svg"|"copy-png"|"pool"|"timeline"|"drag"=>export_one(action.to_string()),
 "batch-png"|"batch-svg"|"batch-pool"=>export_batch(action.to_string()),
 "project-export"|"looks-export"=>{let (v,name)=with(|a|if action=="project-export"{(json!({"version":2,"items":a.items}),"Icon Studio.iconstudio")}else{(json!({"format":"icon-studio-looks","version":1,"looks":a.looks}),"Icon Studio.iconlooks")});spawn_local(async move{if let Err(e)=save_bytes(v.to_string().into_bytes(),name,"application/json").await{toast(e)}});},
 "pack-all"|"pack-color"=>{change(|a|{if let Some(packs)=a.catalog["collections"].as_array(){a.pack_selection=packs.iter().filter(|p|action=="pack-all"||flag(p,"color")).map(|p|text(p,"prefix").to_string()).collect();}});render()},
 "download-packs"=>{let packs=with(|a|a.pack_selection.iter().cloned().collect::<Vec<_>>());if packs.is_empty(){toast("Select at least one collection");return}change(|a|a.library_progress="Downloading selected collections…".into());render();spawn_local(async move{match api("downloadLibrary",json!({"prefixes":packs})).await{Ok(v)=>{change(|a|a.library_progress=format!("{} collections downloaded",v["downloaded"]));render()},Err(e)=>toast(e)}});},
 "archive-export"=>{let id=with(|a|a.archive_project.clone());spawn_local(async move{match api("exportArchive",json!({"id":id})).await{Ok(_)=>toast("Archive exported"),Err(e)=>toast(e)}});},_=>{}
 }
}
fn file_picker(id:&str){if let Some(el)=document().get_element_by_id(id).and_then(|e|e.dyn_into::<HtmlInputElement>().ok()){el.set_value("");el.click();}}
fn import_files(files:FileList){let files=(0..files.length().min(200)).filter_map(|i|files.item(i)).collect::<Vec<_>>();spawn_local(async move{for file in files{if let Err(e)=import_file(file).await{toast(e)}}});}
async fn import_file(file:File)->Result<(),String>{let f=read_file(file).await.map_err(js_error)?;let name=js_sys::Reflect::get(&f,&"name".into()).map_err(js_error)?.as_string().unwrap_or_default();let bytes=js_sys::Uint8Array::new(&js_sys::Reflect::get(&f,&"bytes".into()).map_err(js_error)?).to_vec();let lower=name.to_lowercase();
 if lower.ends_with(".iconstudio")||lower.ends_with(".json")||lower.ends_with(".iconlooks"){let v:Value=serde_json::from_slice(&bytes).map_err(|_|"Invalid JSON file")?;if v["format"]=="icon-studio-looks"{let looks=v["looks"].as_array().ok_or("Invalid preset file")?;if looks.len()>200{return Err("Choose up to 200 presets".into())}let looks:Vec<_>=looks.iter().map(|l|json!({"id":uuid(),"name":safe_name(text(l,"name")),"style":look_style(&l["style"])})).collect();change(|a|a.looks.extend(looks));persist();render();}else{let items=validate_project(&v)?;mutate(|a|{a.items=items;a.active=0;a.selected.clear();a.modal.clear();});}return Ok(())}
 let mut svg=String::new();let mut image=String::new();if lower.ends_with(".svg"){svg=sanitize_svg(std::str::from_utf8(&bytes).map_err(|_|"SVG must use UTF-8")?)?;}else{let mime=if bytes.starts_with(b"\x89PNG\r\n\x1a\n"){"image/png"}else if bytes.starts_with(&[0xff,0xd8,0xff]){"image/jpeg"}else if bytes.starts_with(b"RIFF")&&bytes.get(8..12)==Some(b"WEBP"){"image/webp"}else{return Err("Import SVG, PNG, JPG or WebP files".into())};image=format!("data:{mime};base64,{}",STANDARD.encode(bytes));}
 let name=name.rsplit_once('.').map(|(n,_)|n).unwrap_or(&name).to_string();mutate(|a|{if a.items.len()>=200{a.toast="A collection holds up to 200 icons".into();return}let style=a.items.get(a.active).map(|i|i.style.clone()).unwrap_or_else(defaults);let n=unique_names(vec![name],a.items.iter().map(|i|i.name.clone()).collect())[0].clone();a.items.push(Item::new(uuid(),n,svg,image,style));a.active=a.items.len()-1;});Ok(())
}
fn remove_background(){let Some(item)=active()else{return};if !flag(&item.style,"removeBg"){return}change(|a|a.busy=true);render();spawn_local(async move{let result=background::remove(&item).await;change(|a|a.busy=false);match result{Ok(image)=>{change(|a|{if let Some(it)=a.items.iter_mut().find(|it|it.id==item.id){if it.style==item.style{it.processed_image=image;}}});persist();render()},Err(e)=>toast(e)}});}
fn export_one(kind:String){if with(|a|a.busy){return}let Some(item)=active()else{return};let(size,glyph)=with(|a|(a.export_size,a.glyph_only));change(|a|a.busy=true);render();spawn_local(async move{let result:Result<(),String>=async{
 let svg=build_svg(&item,size,glyph);let native=with(|a|a.native);
 if !native&&kind=="copy-svg"{JsFuture::from(window().navigator().clipboard().write_text(&svg)).await.map_err(js_error)?;toast("SVG copied");return Ok(())}if !native&&kind=="svg"{save_bytes(svg.into_bytes(),&format!("{}.svg",item.name),"image/svg+xml").await?;return Ok(())}
 let bytes=png(&item,size,glyph).await?;
 let file=if native{api("generate",json!({"item":item,"base64":STANDARD.encode(&bytes),"svg":svg,"expectedProjectId":with(|a|a.project["id"].clone())})).await?}else{Value::Null};
 match kind.as_str(){"copy-svg"=>{JsFuture::from(window().navigator().clipboard().write_text(&svg)).await.map_err(js_error)?;toast("SVG copied");},"svg"=>save_bytes(svg.into_bytes(),&format!("{}.svg",item.name),"image/svg+xml").await?,"copy-png"=>{write_clipboard(&js_sys::Uint8Array::from(bytes.as_slice()),"image/png").await.map_err(js_error)?;toast("PNG copied");},"pool"|"timeline"|"drag"=>{api(&kind,json!({"id":file["id"],"expectedProjectId":with(|a|a.project["id"].clone())})).await?;if kind!="drag"{toast(if kind=="pool"{"Added to Media Pool"}else{"Added above overlapping clips"})}},_=>{save_bytes(bytes,&format!("{}.png",item.name),"image/png").await?;}}
 Ok(())}.await;change(|a|a.busy=false);if let Err(e)=result{toast(e)}else{render()}});}
fn export_batch(kind:String){if with(|a|a.busy){return}selected_or_active();let(items,size,glyph,project,native)=with(|a|(a.items.iter().filter(|it|a.selected.contains(&it.id)).cloned().collect::<Vec<_>>(),a.export_size,a.glyph_only,a.project["id"].clone(),a.native));change(|a|a.busy=true);render();spawn_local(async move{let result:Result<(),String>=async{let mut files=vec![];let mut entries=HashMap::new();for it in items{let svg=build_svg(&it,size,glyph);let png=if native||kind!="batch-svg"{png(&it,size,glyph).await?}else{vec![]};let bytes=if kind=="batch-svg"{svg.clone().into_bytes()}else{png.clone()};if native{let file=api("generate",json!({"item":it,"svg":svg,"base64":STANDARD.encode(png),"expectedProjectId":project})).await?;files.push(file["id"].clone());}if kind!="batch-pool"{entries.insert(format!("{}.{}",it.name,if kind=="batch-svg"{"svg"}else{"png"}),bytes);}}
 if kind=="batch-pool"{api("batchImport",json!({"ids":files,"expectedProjectId":project})).await?;toast("Selected icons added to Media Pool");}else{let zip=icon_studio_core::zip_files(&entries)?;save_bytes(zip,"Icon Studio.zip","application/zip").await?;}Ok(())}.await;change(|a|a.busy=false);if let Err(e)=result{toast(e)}else{render()}});}
fn load_archive(){let id=with(|a|a.archive_project.clone());spawn_local(async move{match api("archiveList",json!({"id":id})).await{Ok(v)=>{change(|a|a.archive=v);render()},Err(e)=>toast(e)}});}
fn archive_action(kind:&str,id:&str){let kind=kind.to_string();let id=id.to_string();spawn_local(async move{if let Err(e)=api(&kind,json!({"id":id,"expectedProjectId":with(|a|a.project["id"].clone())})).await{toast(e)}});}
pub async fn sync_project()->Result<(),String>{
 let ctx=api("context",json!({})).await?;let project=ctx["project"].clone();if with(|a|a.project["id"]==project["id"]){return Ok(())}
 let workspace=ctx["workspace"].clone();let items=if workspace.is_object(){validate_project(&workspace).unwrap_or_default()}else{vec![]};change(|a|{a.project=project;a.items=items;a.active=0;a.selected.clear();a.undo.clear();a.redo.clear();if a.items.is_empty(){let svg=a.starter.get("apple:photos").or_else(||a.starter.values().next()).cloned().unwrap_or("<svg viewBox='0 0 24 24'><path d='m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3Z'/></svg>".into());let style=if ctx["look"]["style"].is_object(){clean_style(&ctx["look"]["style"])}else{defaults()};a.items.push(Item::new(uuid(),"photos".into(),svg,"".into(),style));}});render();Ok(())
}
