use super::*;
use std::fmt::Write;
pub const PALETTES:[(&str,&str,&str);14]=[("Iris","#a897f5","#6664df"),("Ocean","#64c9f8","#1976e7"),("Mint","#6ce0bd","#20a17b"),("Sunset","#ffb88a","#ee6b85"),("Messages","#63e77b","#25ad45"),("Mail","#47a2f6","#2770df"),("Music","#fb5c74","#fa233b"),("Podcasts","#d65cf3","#8e28d7"),("Notes","#fcd116","#f8b600"),("Health","#fd475d","#e11132"),("Weather","#5ac8fa","#0a84ff"),("Graphite","#555560","#22222a"),("Settings","#8e8e93","#636366"),("Dark","#2c2c2e","#1c1c1e")];
pub fn icon(name:&str)->String {let d=match name{
 "search"=>"M21 21l-6-6M17 10a7 7 0 1 0-14 0 7 7 0 0 0 14 0Z",
 "download"=>"M12 3v12m-5-5 5 5 5-5M3 16v5h18v-5",
 "project"|"folder"=>"M3 7V4h6l3 3h9v13H3Z",
 "looks"=>"M6 3h12v18l-6-4-6 4Z",
 "settings"=>"M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8ZM12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2",
 "archive"=>"M3 3h18v5H3ZM5 8v13h14V8M9 12h6",
 "theme"=>"M20 14a8 8 0 0 1-10-10 8 8 0 1 0 10 10Z",
 "pin"=>"M8 3h8l-1 7 4 5H5l4-5ZM12 15v7",
 "undo"=>"M8 4 3 9l5 5M3 9h10a7 7 0 0 1 0 14",
 "redo"=>"m16 4 5 5-5 5m5-5H11a7 7 0 0 0 0 14",
 "copy"=>"M8 8h13v13H8ZM16 8V3H3v13h5",
 "trash"=>"M3 6h18M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7m4-7v7",
 "rename"=>"M3 4h18M12 4v16M7 20h10",
 "pool"=>"M3 5h18v15H3ZM3 10h18M8 5v5m8-5v5M8 15h8m-4-3v6",
 "timeline"=>"M3 5h18v5H3ZM3 14h7v5H3Zm10 0h8v5h-8ZM12 2v20",
 "library"=>"M3 3h7v7H3Zm11 0h7v7h-7ZM3 14h7v7H3Zm11 0h7v7h-7Z",
 "inspector"=>"M3 6h18M3 12h18M3 18h18M8 3v6m8 0v6M10 15v6",
 "plus"=>"M12 4v16M4 12h16",
 "check"=>"m4 12 5 5L20 6",
 "close"=>"m5 5 14 14M19 5 5 19",
 "sparkle"=>"m12 3 3 6 6 3-6 3-3 6-3-6-6-3 6-3Z",
 "upload"=>"M12 16V3m-5 5 5-5 5 5M3 16v5h18v-5",
 _=>"M4 4h16v16H4Z"};format!("<svg class=\"symbol\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\"><path d=\"{d}\"/></svg>")}
pub fn btn(action:&str,symbol:&str,label:&str,class:&str)->String{format!("<button class=\"btn {class}\" data-action=\"{}\" title=\"{}\" aria-label=\"{}\">{}<span class=\"label\">{}</span></button>",escape(action),escape(label),escape(label),icon(symbol),escape(label))}
fn field(key:&str,label:&str,kind:&str,value:&str)->String{format!("<label class=\"field\"><span>{}</span><input data-field=\"{}\" type=\"{kind}\" value=\"{}\"></label>",escape(label),escape(key),escape(value))}
fn slider(s:&Value,key:&str,label:&str,min:f64,max:f64,step:f64)->String{let val=number(s,key);format!("<div class=\"field\"><label for=\"{key}\">{label}</label><span class=\"value\" id=\"value-{key}\">{val:.1}</span></div><input id=\"{key}\" data-field=\"style-{key}\" data-style=\"{key}\" type=\"range\" min=\"{min}\" max=\"{max}\" step=\"{step}\" value=\"{val}\">")}
fn toggle(s:&Value,key:&str,label:&str)->String{format!("<label class=\"field\"><span>{label}</span><input type=\"checkbox\" data-field=\"style-{key}\" data-style=\"{key}\" {}></label>",if flag(s,key){"checked"}else{""})}
fn colors(s:&Value,key:&str)->String{format!("<div class=\"color-row\"><input type=\"color\" aria-label=\"{key}\" data-field=\"color-{key}\" data-style=\"{key}\" value=\"{}\"><input type=\"text\" aria-label=\"{key} hex\" data-field=\"hex-{key}\" data-style=\"{key}\" value=\"{}\" maxlength=\"7\"></div>",text(s,key),text(s,key))}
fn segments(s:&Value,key:&str,options:&[(&str,&str)])->String{format!("<div class=\"segments\">{}</div>",options.iter().map(|(id,label)|format!("<button class=\"{}\" data-action=\"style:{key}:{id}\">{label}</button>",if text(s,key)==*id{"active"}else{""})).collect::<String>())}
fn palettes(target:&str)->String{format!("<div class=\"palette-title\">PALETTES</div><div class=\"palette\">{}</div>",PALETTES.iter().enumerate().map(|(i,(name,a,b))|format!("<button class=\"swatch\" title=\"{name}\" aria-label=\"{name}\" data-action=\"palette:{target}:{i}\" style=\"background:linear-gradient(145deg,{a},{b})\"></button>")).collect::<String>())}
fn inspector(a:&App)->String{
 let fallback=defaults();let s=a.items.get(a.active).map(|i|&i.style).unwrap_or(&fallback);let mut out=String::new();
 if a.panel=="style"{
 out+=&format!("<section class=\"group\"><h3>Background</h3>{}",segments(s,"bgType",&[("solid","Solid"),("gradient","Gradient"),("transparent","None")]));
 if text(s,"bgType")!="transparent"{out+=&colors(s,"bgColor1");if text(s,"bgType")=="gradient"{out+=&colors(s,"bgColor2");out+=&slider(s,"bgAngle","Angle",0.,360.,1.);}out+=&palettes("bg");out+="<details><summary>Solid colors</summary><div class=\"palette\">";for (_,c,_)in PALETTES{out+=&format!("<button class=\"swatch\" style=\"background:{c}\" aria-label=\"{c}\" data-action=\"solid:bg:{c}\"></button>");}out+="</div></details>";}out+="</section>";
 out+=&format!("<section class=\"group\"><h3>Shape &amp; finish</h3>{}<div class=\"segments\"><button data-action=\"radius:0\">Square</button><button data-action=\"radius:22.5\">Squircle</button><button data-action=\"radius:50\">Circle</button></div>{}{}<details><summary>More effects</summary>",slider(s,"borderRadius","Corner radius",0.,50.,0.5),toggle(s,"enableShadow","Soft shadow"),toggle(s,"enableInnerLight","Light edge"));
 for(k,l)in [("enableBevel","Bevel"),("enableClassicSweep","Gloss"),("enableGlyphShadow","Glyph shadow"),("enableGlow","Glow"),("enableOutline","Outline"),("enableGrain","Grain"),("enableVignette","Vignette"),("enableAmbientLight","Ambient light"),("enableMonochrome","Monochrome")]{out+=&toggle(s,k,l)}
 out+=&colors(s,"effectColor");for(k,l,max)in [("outlineWidth","Outline width",50.),("glowStrength","Glow strength",100.),("grainAmount","Grain amount",100.),("shadowStrength","Shadow strength",100.)]{out+=&slider(s,k,l,0.,max,1.);}out+="</details></section>";
 }else{
 out+=&format!("<section class=\"group\"><h3>Icon color</h3>{}",segments(s,"iconColorMode",&[("original","Original"),("solid","Solid"),("gradient","Gradient")]));if text(s,"iconColorMode")!="original"{out+=&colors(s,"iconColor1");if text(s,"iconColorMode")=="gradient"{out+=&colors(s,"iconColor2");out+=&slider(s,"iconAngle","Angle",0.,360.,1.);}out+=&palettes("fg");}out+="</section><section class=\"group\"><h3>Transform</h3>";for(k,l,min,max,step)in [("iconScale","Size",0.05,1.5,0.01),("iconRotation","Rotation",-180.,180.,1.),("offsetX","Horizontal",-50.,50.,1.),("offsetY","Vertical",-50.,50.,1.),("glyphOpacity","Opacity",0.,100.,1.)]{out+=&slider(s,k,l,min,max,step)}out+="</section>";
 out+=&format!("<section class=\"group\"><h3>Image background</h3>{}<label class=\"field\"><span>Method</span><select data-field=\"style-bgRemoveMode\" data-style=\"bgRemoveMode\">",toggle(s,"removeBg","Remove background"));for(id,name)in [("smart","AI subject"),("auto","Edge detection"),("white","White"),("black","Black"),("custom","Custom color")]{out+=&format!("<option value=\"{id}\" {}>{name}</option>",if text(s,"bgRemoveMode")==id{"selected"}else{""});}out+="</select></label>";out+=&slider(s,"bgTolerance","Tolerance",0.,255.,1.);out+=&toggle(s,"edgeOnly","Edges only");if text(s,"bgRemoveMode")=="custom"{out+=&colors(s,"bgRemoveColor");}out+="</section>";
 }out
}
fn card(a:&App,i:&Icon,quick:bool,index:usize)->String{
 let id=i.id();let src=a.artwork.get(&id).cloned().unwrap_or_else(||svg_data("<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'><rect x='5' y='5' width='14' height='14' rx='4' fill='#888' opacity='.2'/></svg>"));
 let fav:Vec<String>=local_get("icon-studio-favorites").and_then(|v|serde_json::from_str(&v).ok()).unwrap_or_default();
 format!("<div class=\"icon-card {}\" role=\"button\" tabindex=\"0\" data-action=\"add:{}\" title=\"{}\" aria-label=\"Add {}\"><img src=\"{}\" alt=\"\" loading=\"lazy\"><span>{}</span><button class=\"favorite {}\" data-action=\"favorite:{}\" aria-label=\"Favorite {}\">{}</button></div>",if quick&&index==a.quick_index{"focused"}else{""},escape(&id),escape(&id),escape(&i.title()),escape(&src),escape(&i.title()),if fav.contains(&id){"saved"}else{""},escape(&id),escape(&i.title()),if fav.contains(&id){"♥"}else{"♡"})
}
pub fn view(a:&App)->String{
 let mut out=String::from("<div class=\"studio\"><header class=\"topbar\"><div class=\"brand\"><span class=\"brand-mark\">");out+=&icon("sparkle");out+="</span><div><b>Icon Studio</b><small>by Sakib</small></div></div>";
 if a.native{out+=&format!("<span class=\"project-name\">{}</span>",escape(text(&a.project,"name")));if flag(&a.settings,"appHost")&&!flag(&a.settings,"resolveConnected"){out+=&btn("connect-resolve","pool","Connect Resolve", "");}out+=&btn("pin","pin","Always on top",if flag(&a.settings,"alwaysOnTop"){"active"}else{""});}
 for(action,sym,label)in [("library","library","Library"),("inspector","inspector","Inspector")]{out+=&btn(action,sym,label,"compact-toggle");}
 out+=&btn("theme","theme","Theme","");out+=&btn("project","project","Project","");out+=&btn("looks","looks","Looks","");if a.native{out+=&btn("archive","archive","Archive","");}out+=&btn("settings","settings","Settings","");
 if !a.native{out+=&format!("<a class=\"btn download-script\" title=\"Download Windows app\" href=\"https://github.com/toolatebysakib/icon-studio/releases/latest/download/IconStudio-Setup.exe\">{}<span class=\"label\">App</span></a>",icon("download"));}out+=&btn("export","download","Export","primary");out+="</header><div class=\"workspace\">";
 out+=&format!("<aside class=\"library {}\"><div class=\"side-title\"><span>Library</span>{}</div><div class=\"library-controls\"><div class=\"search-field\"><input type=\"search\" placeholder=\"Search icons…\" aria-label=\"Search icons\" data-field=\"search\" value=\"{}\"><button data-action=\"quick\" title=\"{}\">⌘</button></div><div class=\"tabs\">",if a.library_open{"open"}else{""},btn("library","close","Close","drawer-close"),escape(&a.query),escape(&a.shortcut.label()));
 for(id,label)in [("explore","Explore"),("favorites","Favorites"),("imports","Imports")]{out+=&format!("<button data-action=\"tab:{id}\" class=\"{}\">{label}</button>",if a.tab==id{"active"}else{""});}
 out+="</div><select aria-label=\"Icon collection\" data-field=\"category\">";for(id,label)in [("featured","Featured"),("color","Color &amp; detail"),("all","All collections")]{out+=&format!("<option value=\"{id}\" {}>{label}</option>",if a.category==id{"selected"}else{""});}
 if let Some(packs)=a.catalog["collections"].as_array(){for p in packs{out+=&format!("<option value=\"{}\" {}>{} · {}</option>",text(p,"prefix"),if a.category==text(p,"prefix"){"selected"}else{""},escape(text(p,"name")),p["count"]);}}
 out+=&format!("</select><div class=\"count\"><span>{} icons</span><span>{} collections</span></div></div><div class=\"library-grid\">",a.catalog["count"].as_u64().unwrap_or(a.starter.len()as u64),a.catalog["collections"].as_array().map_or(0,|v|v.len()));
 if a.tab=="imports"{for(i,it)in a.items.iter().enumerate().filter(|(_,it)|it.source=="Imported"){out+=&format!("<button class=\"icon-card\" data-action=\"active:{i}\"><img src=\"{}\" alt=\"\"><span>{}</span></button>",svg_data(&build_svg(it,64,false)),escape(&it.name));}}else{for(i,it)in a.results.iter().enumerate(){out+=&card(a,it,false,i);}if a.results.is_empty(){out+="<div class=\"empty\">No matching icons</div>";}}
 out+=&format!("</div><div class=\"library-footer\">{}{} </div></aside>",btn("import","upload","Import icons","outlined"),btn("quick","search","Quick search",""));
 out+="<main class=\"center\"><div class=\"center-toolbar\"><span>Workspace</span><span>›</span>";out+=&format!("<strong>{}</strong>",escape(a.items.get(a.active).map(|it|it.name.as_str()).unwrap_or("")));out+=&btn("undo","undo","Undo","");out+=&btn("redo","redo","Redo","");out+="</div>";
 out+=&format!("<section class=\"viewport {}\" aria-label=\"Icon preview\">",if a.checker{"checker"}else{""});if let Some(it)=a.items.get(a.active){out+=&format!("<div class=\"artwork\" style=\"transform:scale({})\"><img id=\"preview\" src=\"{}\" alt=\"{} preview\" draggable=\"{}\" data-action=\"drag\"></div><div class=\"icon-name\"><span id=\"preview-name\">{}</span>{}</div><div class=\"preview-actions\">{}{}{} </div>",a.zoom,svg_data(&build_svg(it,1024,a.glyph_only)),escape(&it.name),a.native,escape(&it.name),btn("rename-current","rename","Rename",""),btn("png","download","Download PNG",""),btn("copy-svg","copy","Copy SVG",""),btn("copy-png","copy","Copy PNG",""));if a.native{out+=&format!("<div class=\"resolve-actions\">{}{} </div>",btn("pool","pool","Media Pool","outlined"),btn("timeline","timeline","Timeline","outlined"));}}else{out+="<div class=\"empty\">Choose an icon to begin</div>";}
 out+=&format!("</section><div class=\"viewport-controls\"><div><button class=\"btn\" data-action=\"zoom-out\" aria-label=\"Zoom out\">−</button><button class=\"btn\" data-action=\"zoom-reset\">{}%</button><button class=\"btn\" data-action=\"zoom-in\" aria-label=\"Zoom in\">+</button></div><div>{}{}</div></div>",(a.zoom*100.)as u32,btn("checker","library","Checkerboard",if a.checker{"active"}else{""}),btn("glyph-only","sparkle","Glyph only",if a.glyph_only{"active"}else{""}));
 out+=&format!("<section class=\"collection\"><div class=\"collection-header\"><strong>Collection <span class=\"badge\">{}</span></strong>{}{}{}{}{} </div><div class=\"collection-strip\">",a.items.len(),btn("select-all","check","Select all",if a.selected.len()==a.items.len()&&!a.selected.is_empty(){"active"}else{""}),btn("batch-style","inspector","Apply style", ""),btn("rename","rename","Rename",""),btn("duplicate","copy","Duplicate",""),btn("delete","trash","Delete",""));
 for(i,it)in a.items.iter().enumerate(){out+=&format!("<div class=\"collection-card {}\" data-action=\"active:{i}\" role=\"button\" tabindex=\"0\"><img id=\"thumb-{i}\" src=\"{}\" alt=\"{}\"><span>{}</span><button class=\"select\" data-action=\"select:{i}\" aria-label=\"Select {}\">{}</button></div>",if i==a.active{"active"}else{""},svg_data(&build_svg(it,80,false)),escape(&it.name),escape(&it.name),escape(&it.name),if a.selected.contains(&it.id){"✓"}else{""});}out+="</div></section></main>";
 out+=&format!("<aside class=\"inspector {}\"><div class=\"side-title\"><span>Inspector</span><small>{}</small>{}</div><div class=\"inspector-tabs\">{}{}</div><div class=\"inspector-scroll\">{}</div><div class=\"inspector-footer\">{}{}</div></aside></div></div>",if a.inspector_open{"open"}else{""},if a.busy{"Processing…"}else{"Live preview"},btn("inspector","close","Close","drawer-close"),btn("panel:style","inspector","Style",if a.panel=="style"{"active"}else{""}),btn("panel:glyph","sparkle","Glyph",if a.panel=="glyph"{"active"}else{""}),inspector(a),btn("reset","undo","Reset style",""),btn("look-save","looks","Save look",""));
 if announcement_active()&&(!a.native||a.settings["libraryCount"].as_u64().unwrap_or(0)<382085){out+=&format!("<aside class=\"library-announcement\" aria-label=\"Expanded icon library\"><button class=\"announcement-dismiss\" data-action=\"dismiss-announcement\" title=\"Dismiss\" aria-label=\"Dismiss library announcement\">{}</button><div class=\"announcement-mark\">{}</div><div class=\"announcement-copy\"><span class=\"announcement-eyebrow\">LIBRARY UPDATE</span><strong>382,000+ icons. More possibilities.</strong><p>Color, detail, and everyday essentials.</p>{}</div></aside>",icon("close"),icon("sparkle"),if flag(&a.settings,"appHost"){btn("download-library-full","download","Download library · 101 MB","announcement-download")}else{String::new()} );}
 if flag(&a.settings,"appHost")&&a.settings["updateNotice"]==true{let u=&a.settings["updates"];let native=flag(u,"appAvailable");out+=&format!("<aside class=\"library-announcement update-announcement\" aria-label=\"Update available\"><button class=\"announcement-dismiss\" data-action=\"update-later\" aria-label=\"Remind me later\">{}</button><div class=\"announcement-mark\">{}</div><div class=\"announcement-copy\"><span class=\"announcement-eyebrow\">UPDATE AVAILABLE</span><strong>{}</strong><p>{}</p>{}</div></aside>",icon("close"),icon("download"),if native{"A new Icon Studio is ready"}else{"Your editor has a new update"},if native{"Install and restart the app."}else{"Reload to get the latest website features."},btn(if native{"update-app"}else{"update-editor"},"download",if a.busy{"Updating…"}else{"Update now"},"announcement-download"));}
 if !a.modal.is_empty(){out+=&modal(a)}if !a.toast.is_empty(){out+=&format!("<div class=\"toast\" role=\"status\"><span>{}</span><button data-action=\"dismiss\" aria-label=\"Dismiss\">×</button></div>",escape(&a.toast));}out+="<input id=\"file-input\" type=\"file\" accept=\".svg,.png,.jpg,.jpeg,.webp,.iconstudio,.iconlooks,.json\" multiple hidden><input id=\"project-input\" type=\"file\" accept=\".iconstudio,.iconlooks,.json\" hidden>";out
}
fn modal(a:&App)->String{
 let title=match a.modal.as_str(){"quick"=>"Quick search","settings"=>"Settings","looks"=>"Looks","rename"=>"Rename icons","project"=>"Project","archive"=>"Generated icons","export"=>"Export",_=>"Icon Studio"};
 let mut out=format!("<div class=\"modal-backdrop\" data-action=\"backdrop\"><section class=\"modal {}\" role=\"dialog\" aria-modal=\"true\" aria-label=\"{title}\"><div class=\"modal-header\">",if a.modal=="quick"{"search-modal"}else{""});if a.modal=="quick"{out+=&icon("search");out+=&format!("<input id=\"quick-input\" type=\"search\" data-field=\"quick-search\" value=\"{}\" placeholder=\"Find an icon…\" aria-label=\"Quick search\">",escape(&a.quick_query));}else{out+=&format!("<h2>{title}</h2>");}out+=&btn("close","close","Close","");out+="</div><div class=\"modal-content\">";
 match a.modal.as_str(){
 "quick"=>{out+="<div class=\"quick-grid\">";for(i,it)in a.quick_results.iter().enumerate(){out+=&card(a,it,true,i)}out+=&format!("</div><div class=\"search-status\"><span>{} matches</span><span>↑ ↓ Navigate · Enter Add · Esc Close</span></div>",a.quick_results.len());},
 "project"=>{out+=&format!("<div class=\"modal-actions\">{}{}{}</div><div class=\"muted\">{} icons · autosaved</div>",btn("project-export","download","Save project","outlined"),btn("project-import","folder","Open project","outlined"),btn("new","plus","New collection","outlined"),a.items.len());},
 "looks"=>{out+=&format!("<div class=\"folder-row\"><input data-field=\"look-name\" value=\"{}\" placeholder=\"Name this look\" aria-label=\"Preset name\">{}</div><div class=\"looks-grid\">",escape(&a.look_name),btn("look-save-confirm","check","Save","primary"));for(i,look)in a.looks.iter().enumerate(){let it=Item::new("look".into(),"".into(),"<svg viewBox='0 0 24 24'><path fill='white' d='m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3Z'/></svg>".into(),"".into(),look["style"].clone());out+=&format!("<div class=\"look-card\"><button data-action=\"look-apply:{i}\"><img src=\"{}\" alt=\"\"><span>{}</span></button><button class=\"delete\" data-action=\"look-delete:{i}\" aria-label=\"Delete preset\">×</button></div>",svg_data(&build_svg(&it,80,false)),escape(text(look,"name")));}out+=&format!("</div><div class=\"modal-actions\">{}{}</div>",btn("looks-import","folder","Import looks","outlined"),btn("looks-export","download","Export looks","outlined"));},
 "rename"=>{let r=&a.rule;out+="<div class=\"form-grid\">";for(k,l,v)in [("template","Template",r.template.as_str()),("prefix","Prefix",r.prefix.as_str()),("suffix","Suffix",r.suffix.as_str()),("find","Find",r.find.as_str()),("replace","Replace",r.replace.as_str())]{out+=&format!("<label>{l}<input data-field=\"rename-{k}\" value=\"{}\"></label>",escape(v));}out+=&format!("<label>Start<input type=\"number\" min=\"0\" data-field=\"rename-start\" value=\"{}\"></label><label>Padding<input type=\"number\" min=\"0\" max=\"12\" data-field=\"rename-padding\" value=\"{}\"></label><label>Case<select data-field=\"rename-case\">",r.start,r.padding);for id in ["keep","lower","upper","title","kebab","snake","camel"]{out+=&format!("<option value=\"{id}\" {}>{id}</option>",if r.case==id{"selected"}else{""})}out+=&format!("</select></label><label class=\"field\">Regular expression<input type=\"checkbox\" data-field=\"rename-regex\" {}></label><label class=\"field\">Case sensitive<input type=\"checkbox\" data-field=\"rename-caseSensitive\" {}></label></div><span class=\"muted\">&#123;name&#125; · &#123;original&#125; · &#123;n&#125; · &#123;date&#125;</span><table class=\"rename-preview\">",if r.regex{"checked"}else{""},if r.case_sensitive{"checked"}else{""});match rename(&a.items,&a.selected,&a.rule,&events::today()){Ok(rows)=>{for(id,n)in rows{if let Some(it)=a.items.iter().find(|it|it.id==id){let _=write!(out,"<tr><td>{}</td><td>→ {}</td></tr>",escape(&it.name),escape(&n));}}},Err(e)=>out+=&format!("<tr><td>{}</td></tr>",escape(&e))};out+=&format!("</table><div class=\"modal-actions\">{}</div>",btn("rename-apply","check","Apply names","primary"));},
 "export"=>{out+=&format!("<div class=\"form-grid\"><label>Resolution<select data-field=\"export-size\">{}
</select></label><label class=\"field\">Glyph only<input type=\"checkbox\" data-field=\"glyph-only\" {}></label></div><div class=\"modal-actions\">{}{}{}{} </div>",[256,512,1024,2048,4096].iter().map(|size|format!("<option value=\"{size}\" {}>{size} × {size}</option>",if a.export_size==*size{"selected"}else{""})).collect::<String>(),if a.glyph_only{"checked"}else{""},btn("png","download","Download PNG","primary"),btn("svg","download","Download SVG","outlined"),btn("batch-png","download","Batch PNG","outlined"),btn("batch-svg","download","Batch SVG","outlined"));if a.native{out+=&btn("batch-pool","pool","Batch Media Pool","outlined");}},
 "settings"=>settings(a,&mut out),
 "archive"=>{out+="<select data-field=\"archive-project\"><option value=\"\">All projects</option>";if let Some(ps)=a.archive["projects"].as_array(){for p in ps{let id=text(p,"id");out+=&format!("<option value=\"{}\" {}>{}</option>",escape(id),if id==a.archive_project{"selected"}else{""},escape(text(p,"name")));}}out+="</select><div class=\"looks-grid\">";if let Some(files)=a.archive["files"].as_array(){for f in files{let id=text(f,"id");out+=&format!("<article class=\"look-card\"><img src=\"/generated/{}\" alt=\"\"><span>{}</span><small class=\"muted\">{}</small><div class=\"modal-actions\">{}{}{} </div></article>",escape(&format!("{id}{}",if flag(f,"previewSvg"){".svg"}else{""})),escape(text(f,"name")),escape(text(f,"projectName")),btn(&format!("archive-pool:{id}"),"pool","Media Pool",""),btn(&format!("archive-timeline:{id}"),"timeline","Timeline",""),btn(&format!("archive-reveal:{id}"),"folder","Show file",""));}}out+=&format!("</div><div class=\"modal-actions\">{}</div>",btn("archive-export","download","Export archive","outlined"));},_=>{}
 }out+="</div></section></div>";out
}
fn settings(a:&App,out:&mut String){
 if flag(&a.settings,"appHost"){*out+=&format!("<h3>Desktop app</h3><div class=\"muted\">Version {} · Editor {}</div><div class=\"modal-actions\">{}{} </div><div class=\"progress\">{}</div>",escape(text(&a.settings,"appVersion")),escape(text(&a.settings,"editorVersion")),btn("check-updates","download","Check for updates","outlined"),btn("connect-resolve","pool",if flag(&a.settings,"resolveConnected"){"Resolve connected"}else{"Connect Resolve"},"outlined"),escape(text(&a.settings,"updateStatus")));}

 *out+=&format!("<h3>Appearance</h3><div class=\"segments\"><button data-action=\"theme-light\" class=\"{}\">Light</button><button data-action=\"theme-dark\" class=\"{}\">Dark</button></div><h3>Quick search</h3><select data-field=\"shortcut-preset\">",if a.theme=="light"{"active"}else{""},if a.theme=="dark"{"active"}else{""});for i in 0..5{let s=Shortcut::preset(i);*out+=&format!("<option value=\"{i}\" {}>{}{}</option>",if a.shortcut==s{"selected"}else{""},s.label(),if i==0{" (default)"}else{""});}*out+=&format!("<option value=\"custom\" {}>Custom</option></select><div class=\"folder-row\"><span>{}</span>{}</div>",if (0..5).all(|i|a.shortcut!=Shortcut::preset(i)){"selected"}else{""},if a.recording{"Press a key combination…".into()}else{escape(&a.shortcut.label())},btn("record","rename",if a.recording{"Cancel"}else{"Record shortcut"},"outlined"));
 if a.native{*out+="<h3>Folders</h3>";for(k,label)in [("rawFolder","Raw icon library"),("outputFolder","Generated icons")]{*out+=&format!("<div class=\"muted\">{label}</div><div class=\"folder-row\"><span title=\"{}\">{}</span>{}</div>",escape(text(&a.settings,k)),escape(if text(&a.settings,k).is_empty(){"Choose a folder"}else{text(&a.settings,k)}),btn(&format!("folder:{k}"),"folder","Choose","outlined"));}*out+="<h3>Timeline</h3><select data-field=\"setting-trackMode\">";for(id,label)in [("auto","Automatic · above overlapping clips"),("manual","Manual track")]{*out+=&format!("<option value=\"{id}\" {}>{label}</option>",if text(&a.settings,"trackMode")==id{"selected"}else{""});}*out+="</select>";if text(&a.settings,"trackMode")=="manual"{*out+=&field("setting-track","Video track","number",&a.settings["track"].to_string());*out+="<select data-field=\"setting-position\">";for(id,label)in [("playhead","At playhead"),("end","At end")]{*out+=&format!("<option value=\"{id}\" {}>{label}</option>",if text(&a.settings,"position")==id{"selected"}else{""});}*out+="</select>";}*out+="<span class=\"muted\">PNG duration follows Resolve’s Standard Still Duration.</span>";}
 *out+=&format!("<h3>Icon library</h3><div class=\"muted\">{} icons · {} collections · {:.1} MB compressed</div><input data-field=\"pack-search\" placeholder=\"Find a collection…\" value=\"{}\"><div class=\"pack-list\">",a.catalog["count"].as_u64().unwrap_or(0),a.catalog["collections"].as_array().map_or(0,|v|v.len()),number(&a.catalog,"compressedBytes")/1e6,escape(&a.pack_query));if let Some(packs)=a.catalog["collections"].as_array(){for p in packs{if !format!("{} {}",text(p,"name"),text(p,"prefix")).to_lowercase().contains(&a.pack_query.to_lowercase()){continue}let id=text(p,"prefix");*out+=&format!("<div class=\"pack-row\"><label><input type=\"checkbox\" data-field=\"pack-{id}\" {}><span>{}</span></label><small>{} · {:.1} MB</small><a href=\"{}\" target=\"_blank\" rel=\"noopener\" title=\"License\">↗</a></div>",if a.pack_selection.contains(id){"checked"}else{""},escape(text(p,"name")),p["count"],number(p,"bytes")/1e6,escape(text(&p["license"],"url")));}}*out+="</div><div class=\"modal-actions\">";*out+=&btn("pack-color","sparkle","Select colorful","outlined");*out+=&btn("pack-all","check","Select all","outlined");if a.native{*out+=&btn("download-packs","download","Download selected","primary");}else{*out+="<a class=\"btn primary\" href=\"https://github.com/toolatebysakib/icon-studio/releases/download/v4.0.0/icon-library-rust.zip\">Download full library</a>";}*out+=&format!("</div><div class=\"progress\">{}</div><a class=\"btn outlined\" href=\"https://github.com/toolatebysakib/icon-studio/releases/latest/download/IconStudio-Setup.exe\">{} Download Windows app</a><a class=\"btn outlined\" href=\"https://github.com/toolatebysakib/icon-studio/releases/latest/download/icon-studio-resolve.zip\">Classic Resolve script</a><a class=\"license-info\" href=\"library/LICENSES.txt\" target=\"_blank\">Collection licenses and credits</a>",escape(&a.library_progress),icon("download"));
}
